sample_app/config/routes.rb
SampleApp::Application.routes.draw do
  

  resources :users
  resources :sessions, :only => [:new,:create,:destroy]
  resources :microposts, :only => [:create,:destroy]
  
  get "users/new"
  root :to => "pages#home"

  get '/contact',:to => 'pages#contact'
  get '/about',:to => 'pages#about'
  get '/pricing',:to => 'pages#pricing'
  get '/help',:to => 'pages#help'
  get '/home',:to => 'pages#home'
  get '/signup', :to => "users#new"
  get '/signin', :to => "sessions#new"
  get '/signout', :to => "sessions#destroy"
  post '/search', :to => "pages#search"

end

sample_app/app/models/link_tag.rb
class LinkTag < ActiveRecord::Base
end

sample_app/app/models/micropost.rb
class Micropost < ActiveRecord::Base
	attr_accessible :content ,:tag
	belongs_to :user 

	#has_many :link_tag
	#has_many :tag , :through => :link_tag
	#has_and_belongs_to_many :tags

	validates :content , :presence => true, :length => {:maximum => 380 }
	validates :user_id , :presence => true
	default_scope :order => 'microposts.created_at DESC'
  
end

sample_app/app/models/tag.rb
class Tag < ActiveRecord::Base
	attr_accessable :name
	
	#has_many :link_tag
	#has_many :micropost, :through => :link_tag
	has_and_belongs_to :microposts
end

sample_app/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email, :password ,:password_confirmation
	attr_accessor	:password

	has_many :microposts, :dependent => :destroy

	validates :name, 	:presence => true,
						:length	=> {:maximum => 50}
	validates :email, 	:presence => true,
						:uniqueness	=> {:case_sensitive => false}
	validates :password,:presence => true,
						:confirmation => true,
						:length => {:within => 6..40}

	before_save :encrypt_password

	def has_password?(submitted_password)
		encryped_password == encrypt(submitted_password)
	end 

	def feed
		Micropost.where("user_id = ?",id)
	end

	class << self
		def authenticate(email, submitted_password)
			user = find_by_email(email)
			(user && user.has_password?(submitted_password)) ? user : nil
		end

		def authenticate_with_salt(id, cookie_salt)
	      user = find_by_id(id)
	      (user && user.salt == cookie_salt) ? user : nil
	    end

	end

	private 
		def encrypt_password
			self.salt = make_salt if new_record?
			self.encryped_password = encrypt(password)
		end

		def encrypt(string)
			secure_hash("#{salt}--#{string}")
		end

		def make_salt
			secure_hash("#{Time.now.utc}--#{password}")
		end

		def secure_hash(string)
			Digest::SHA2.hexdigest(string)
		end

end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

sample_app/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate
  before_filter :authorized_user, :only => :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    @tag = @micropost.tag
    if @micropost.save
      redirect_to root_path, :flash => { :success => "Micropost created"}
    else
      @feed_items = []#current_user.feed.paginate(:page => params[:page])
      render 'pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_path, :flash => {:success => "Micropost deleted!"}
  end

  private
  def authorized_user
    @micropost = Micropost.find(params[:id])
    redirect_to root_path unless current_user?(@micropost.user)
  end

end

sample_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  	@title = "Home"
    if signed_in?
      @micropost = Micropost.new
      @feed_items = current_user.feed.paginate(:page => params[:page], :per_page => 9)
    end
  end

  def contact
  	@title = "Contact"
  end

  def about
  	@title = "About"
  end

  def help
  	@title = "Help"
  end

  def pricing
    @title = "Pricing"
  end

  def search
    @title = "Searching " + params[:tags]
    @tagsArr = explode(params[:tags],'#')
    @micropost = Micropost.new
    @results = [] 
    @tagsArr.reject! { |t| t.empty? }

    @mytags = []

    if !@tagsArr.nil?
      @first_tags = current_user.feed.first.tag
      current_user.feed.each do |item|
        @feed_tags = explode(item.tag,'#')
        if !@feed_tags.nil?
          @feed_tags.reject! { |t| t.empty? }
          @mytags.push(@feed_tags)


          @tagsArr.each do |tag|
            @feed_tags.each do |ftag|
              if ftag.strip == tag.strip
                @results.push(item)
                break
              end
            end
          end
          
        end
      end
    end

  

    @feed_items = @results.paginate(:page => params[:page], :per_page => 9)
  end
  def explode(tags,ch)
    if !tags.nil?
      tags = tags.downcase
      @categories = tags.split(ch)
    else
      @categories = tags
    end 

  end

end

sample_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign in"
  end

  def create
  	user = User.authenticate(params[:session][:email],
  							 params[:session][:password])
  	if user.nil?
  		flash.now[:error] = "Invalid email/password combination"
  		@title = "Sign in"
	  	render 'new'  	
	  else
	  	sign_in user
	  	redirect_back_or home_path
	  end
  end

  def destroy
  	sign_out
    redirect_to root_path
  end

end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate , :only => [:edit,:index,:update,:destroy]
  before_filter :correct_user , :only => [:edit,:update]
  before_filter :admin_user, :only => :destroy

  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page], :per_page => 9)    
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(:page => params[:page], :per_page => 9)
    @title = @user.name
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_back_or home_path
  	else 
  		@title = "Sign up"
  		render 'new'
  	end
  end

  def edit
    #@user = User.find(params[:id])
    @title = "Edit User"
  end


  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else 
      @title = "Edit User"
      render 'edit'
    end   
  end

  def destroy
    @user.destroy
    redirect_to users_path, :flash => { :success => "User destroyed." }
  end


  private
    

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

  def admin_user
    @user = User.find(params[:id])
    redirect_to(root_path) if !current_user.admin? || current_user?(@user)
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

	def title
		base_title = "Sample App"
		if @title.nil? #there should be question mark for nil 
			base_title
		else
			" #{base_title} | #{ @title }"
		end
	end

	def logo
		image_tag("logo.png",:alt=>"Sample App",:class => "round") 
	end
 
 end

sample_app/app/helpers/microposts_helper.rb
module MicropostsHelper
	def microposts_helper_categories(input)
		if !input.nil?
			@categories = input.split(' ')
		end	
	end
end

sample_app/app/helpers/pages_helper.rb
module PagesHelper
end

sample_app/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def current_user?(user)
		user == current_user
	end
	
	def authenticate
      deny_access unless signed_in?
    end

	def deny_access
  		redirect_to signin_path , :notice =>  "Please sign in to access this page"
    end

  	def store_location
		session[:return_to] = request.fullpath
    end

    def redirect_back_or(default)
    	redirect_to(session[:return_to] || default)
    	clear_return_to
    end

    def clear_return_to
    	session[:return_to] = nil
    end

	private

		def user_from_remember_token
			User.authenticate_with_salt(*remember_token)
			
		end

		def remember_token
			cookies.signed[:remember_token] || [nil,nil]
		end

end
 

sample_app/app/helpers/users_helper.rb
module UsersHelper
end

sample_app/app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<h4>My Account</h4>
				<ul class="list-unstyled">
					<!-- <li><a href="#">Settings</a></li> -->
					<% if signed_in? %>
						<li><%= link_to "Sign out" , signout_path %></li>
						<li><%= link_to "Link Delete" , user_path(current_user) %></li>
						<% if current_user.admin?  %>
							<li><%= link_to "Users" , users_path %></li>
						<% end %>
					<% else %>
						<li><%= link_to "Sign in" , signin_path %></li>
						<li><%= link_to "Sign up" , signup_path %></li>
					<% end %>
					<li><%= link_to "Home" , root_path %></li>
			
				</ul>
			</div><!-- /col-lg-4 -->

			<div class="col-lg-6">
				<h4>LinkRepo</h4>
				<ul class="list-unstyled">
					<li><%= link_to "Help" , help_path %></li>
					<li><%= link_to "Contact" , contact_path %></li>
					<li><%= link_to "Pricing" , pricing_path %></li>
					<!-- <li><a href="#">API</a></li> -->
				</ul>
			</div><!-- /col-lg-4 -->
		</div>
	</div>
</div>

sample_app/app/views/layouts/_header.html.erb
<!-- Static navbar -->
<div class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/">LINK REPO</a>
		</div>
		<div class="navbar-collapse collapse pull-right">
			 <div id="link-search" class="pull-left">
			 	<% if signed_in? %>
					<%= form_tag "/search" do |f| %>
					<%= text_field_tag  'tags', params[:tags], autocomplete: true, placeholder: "#tag", size: 50, autofocus:true %>
					<%end%>
				<%end%>
			 </div>
		</div><!--/.nav-collapse -->
	</div>
</div>

sample_app/app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

<%= stylesheet_link_tag 'linkrepo/css/bootstrap', :media => 'screen'  %>
<%= stylesheet_link_tag 'linkrepo/css/main', :media => 'screen'  %>

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name="description" content="">
		<meta name="author" content="">
<!-- 		<link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">
 -->		
		<title> <%= title %> </title>
		<%= csrf_meta_tag %>
		<%= render 'layouts/stylesheets' %>
		<%= javascript_include_tag  "application" %>

		<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
		<script src="/assets/linkrepo/js/hover.zoom.js"></script>
		<script src="/assets/linkrepo/js/hover.zoom.conf.js"></script>
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
		<![endif]-->

	</head>
	<body>
		<%= render 'layouts/header' %>
		<div id="pagewrapper">
			<div class="container pt">

				<%= yield %>

 			</div>
			<div class="footer-ghost"></div>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>

sample_app/app/views/microposts/_micropost.html.erb
<tr>
	<td class ="microposts">
		<span class ="content"><%= micropost.content %></span></br>
		<span class ="timestamp">Posted <%= time_ago_in_words(micropost.created_at) %> ago.</span></br>
	</td>
	<% #user = micropost.user resque User.find(micropost.user_id) %>
	<% if current_user?(micropost.user) %>
		<td><%= link_to "delete", micropost ,:method => :delete ,
										:confirm => "Are you sure",
										:title => micropost.content	%>
		</td>
	<% end %>
</tr>

sample_app/app/views/pages/about.html.erb
<h1>About Us</h1>
<p>
	This is the about page for the 
	<a href="https://railstutorial.org">Ruby on Rails tutorial</a> sample application
</p>

sample_app/app/views/pages/contact.html.erb
<h1>Contact</h1>
<p> 
	<div>Sinan NAR</div>
	<a href="https://twitter.com/snn_nr">Twitter</a>  </br>
	<a href="https://plus.google.com/+SinanNAR">Google+</a>  </br>
</p>
<p>	
	<div>Burak Koray KÖSE</div>
	<a href="https://twitter.com/burakkoray">Twitter</a>  </br>
	<a href="https://plus.google.com/+burakkoraykose">Google+</a>  </br>
</p>

<p> </p></br>
<p> </p></br>
<p> </p></br>

And some special thanx goes to <b>Furkan TEKTAS</b> for UI design<br>

There is another hero named <b>Sercan GEDIK</b> who explain Rails and help about it to us<br>

sample_app/app/views/pages/help.html.erb
<h1>Help</h1>
<p>
	This is the application for storing links
	<a href="https://github.com/sinannar/sample_app">Codes</a> are available here
	<p> </p></br>
	

</p>

sample_app/app/views/pages/home.html.erb
<% if signed_in? %>
	<%= render 'shared/feed' %>



<%else%>

<div id="ww">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 centered">
				<h1>LinkRepo!</h1>
				<h2>Welcome to Link Repo</h2>
				<p>This is the application for storing links
			<a href="https://github.com/sinannar/sample_app">Codes</a> are available here</p>
				<p>	
					If you do not have account yet!</br>
					<%= link_to "Sign up now!",signup_path,:class => "signup_button round" %></br>
				</p>
				<p>	
					Or you have already one...</br>
					<%= link_to "Sign in" , signin_path %>
				</p>
				<h2>What about pricing?</h2>
				<p>It's totally free!</p>
			</div><!-- /col-lg-8 -->
		</div><!-- /row -->
	</div> <!-- /container -->
</div><!-- /ww -->	
<%end%>

sample_app/app/views/pages/pricing.html.erb
<h1>Pricing</h1>
<p>
	This is totally free</br>
	Feel free to use it
</p>

sample_app/app/views/pages/search.html.erb
<% if signed_in? %>
	<%= render 'shared/feed' %>
	<!-- <p> results: <%= @results %></p>
	<p> feed tags: <%= @feed_tags %></p>
	<p> tagsArr: <%= @tagsArr %></p>
	<p> first_tags: <%= @first_tags %></p>
	<p> mytags: <%= @mytags %></p> -->
<%else%>
	<h1>Home</h1>
	<p>
		<p>
			Welcome to Link Repo</br>

			This is the application for storing links
			<a href="https://github.com/sinannar/sample_app">Codes</a> are available here
		</p>
	</p>
	<p>	
		If you do not have account yet!</br>
		<%= link_to "Sign up now!",signup_path,:class => "signup_button round" %></br>
	</p>
	<p>	
		Or you have already one...</br>
		<%= link_to "Sign in" , signin_path %>
	</p>
	
<%end%>

sample_app/app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(object.errors.count,"error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:
		</h2>	
		<p>There were problems with the following fields:</p>
		<ul>
			<%= object.errors.full_messages.each do |message| %>
				<li><%= message%></li>
			<% end %>
		</ul>
	</div>
	
<% end %>

sample_app/app/views/shared/_feed.html.erb
	<%= render :partial => 'shared/micropost_form'%>
	<% if @feed_items.any? %>
		<%= render :partial => 'shared/feed_item',:collection => @feed_items %>

	<div class="text-center">	
		<%= will_paginate @feed_items, renderer: BootstrapPagination::Rails %>
	</div>
	<% end %>

	<%= javascript_include_tag  "/assets/linkrepo/js/bootstrap.min" %>
	<%= javascript_include_tag  "link-add" %>

		

sample_app/app/views/shared/_feed_item.html.erb
<% if (feed_item_counter )  % 3  == 0  %>
<div class="row mt centered">   
<%end%>

<div class="col-lg-4 link-col">

	<a class="zoom blue" href="http://<%= feed_item.content %>" target="_blank">
		<span class="glyphicon glyphicon-link zoom link-icon"></span>
		<img class="img-responsive" src="http://api.webthumbnail.org?width=360&height=270&screen=1650&url=http://<%= feed_item.content %>" alt="" />
		<div class="tags">
			<% if !microposts_helper_categories(feed_item.tag).nil?  %>
				<% microposts_helper_categories(feed_item.tag).each do |n|%>
					<span class="tag"><%= n %></span>
				<%end%>
			<%end%>
		</div>
		<p class="title"><%= feed_item.content %></p>
	</a>
</div>

<% if (feed_item_counter + 1 ) % 3 == 0  %>
</div><!-- /row -->
<%end%>

sample_app/app/views/shared/_micropost_form.html.erb
<div class="row mt centered link-add-section">   
	<button type="button" class="pull-right add-link-btn btn-lg btn-default" onclick="showlink()">
		<span class="glyphicon glyphicon-plus"></span> Add Link
	</button>
	<%= form_for @micropost, html: {class: "add-url-form"} do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%= f.text_field :content, :placeholder => "url" %>
	<%= f.text_field :tag, :placeholder => "#tag1 #tag2" %>
	<%= f.submit "add link" %>
	<%end%>
</div>

sample_app/app/views/shared/_user_info.html.erb
<div class = "user_info">
	<a href="<%= user_path(current_user) %>">
		<span class = "user_name">
			<%= current_user.name %>
		</span></br>
		<span class = "microposts">
			<%= pluralize(current_user.microposts.count,"micropost") %>
		</span>
	</a>
</div>

sample_app/app/views/users/_fields.html.erb
<%# render 'shared/error_messages'  %>
<div class ="field">
	<%= f.label :name %> <br />
	<%= f.text_field :name %>
</div>
<div class ="field">
	<%= f.label :email %> <br />
	<%= f.text_field :email %>
</div>
<div class ="field">
	<%= f.label :password %> <br />
	<%= f.password_field :password %>
</div>
<div class ="field">
	<%= f.label :password_confirmation ,"Confirmation"%> <br />
	<%= f.password_field :password_confirmation %>
</div>

sample_app/app/views/users/_user.html.erb
<li class="list-group-item">
	<%= link_to user.name ,user %>
	<% if current_user.admin?  %>
	    <span class="badge"><%= link_to "Delete", 
				user, 
				:method => :delete,
				:confirm => 'Are u sure ?' ,
		 		:title => "Delete #{user.name}",
		 		:style => "color:#fff" %></span>
 
	
	<% end %>
</li>

sample_app/app/views/users/edit.html.erb
<h1>Edi User</h1>
<%= form_for(@user) do |f| %>
	<%= render 'fields',:f=>f  %>
	<div class ="actions">
		<%= f.submit "Update" %>
	</div>

<% end %>

sample_app/app/views/users/index.html.erb
<h1>All users</h1>

<ul class = "users list-group">
	<%= render @users %>
</ul>

	<div class="text-center">	
		<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
	</div>

sample_app/app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', :object => f.object %>
	<%= render 'fields' , :f=>f %>
	<div class ="actions">
		<%= f.submit "Sign up" %>
	</div>

<% end %>

sample_app/app/views/users/show.html.erb
<table class="profile" summary="Profile Information">
	<tr>
		<td class="main">
			<h1>
   				<%= @user.name %>
   			</h1>
			<h1>
   				<%= @user.email %>
   			</h1>
   			<% if @user.microposts.any? %>
   				<table class="microposts" summary="User microposts">
   					<%= render @microposts %>
   				</table>
   				<% will_paginate @microposts %>
   			<% end %>
		</td>
		<!-- <td class="sidebar round">
			<strong>Name</strong> <%= @user.name %><br />
			<strong>URL</strong> <%= link_to user_path(@user),@user %><br />
			<strong>Microposts</strong> <%= @user.microposts.count %><br />

		</td> -->
	</tr>
</table>